apiVersion: v1
kind: Service
metadata:
  name: k8s-hello-to-nginx
spec:
  type: LoadBalancer
  selector:
    app: k8s-hello-to-nginx
  ports:
    - port: 3000
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-hello-to-nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: k8s-hello-to-nginx
  template:
    metadata:
      labels:
        app: k8s-hello-to-nginx
    spec:
      containers:
        - name: k8s-hello-to-nginx
          image: snoopy910/k8s-hello-to-nginx
          resources:
            limits:
              memory: "128Mi"
              cpu: "125m"
          ports:
            - containerPort: 8080
